<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
  <OutputType>Exe</OutputType>
  <TargetFramework>net8.0</TargetFramework> <!-- Sua versão pode ser diferente -->
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>disable</Nullable> <!-- A TRAVA FOI DESLIGADA AQUI -->
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="7.0.2" />
  </ItemGroup>

</Project>
